[general]
import = [
  # "~/.config/alacritty/themes/themes/xterm.toml"
  # "~/.config/alacritty/my_theme.toml"
  "~/.config/alacritty/old_school.toml"
]

[env]
TERM = "alacritty"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"

opacity = 0.8
blur = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal.family = "monospace"
size = 12

[cursor]
# style.shape = "Block"
# style.blinking = "Always"

[selection]
save_to_clipboard = true

# [[keyboard.bindings]]
# chars = "\u001B[13;5u"
# key = "Return"
# mods = "Control"

[keyboard]
bindings = [
  { key = "Return", mods = "Control", chars = "\u001B[13;5u" },
  { key = "V", mods = "Control", action = "Paste" },
]
