# Default colors
[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

[colors.normal]
black = "#000000"
red = "#E52E2E"
green = "#52ffcf"
yellow = "#fff182"
blue = "#1376f8"
magenta = "#c792ea"
cyan = "#00fbff"
white = "#FFFFFF"

[colors.bright]
black = "#62686c"
red = "#ff6e67"
green = "#73ffd8"
yellow = "#fcf4ad"
blue = "#378dfe"
magenta = "#ae81ff"
cyan = "#0cbcc0"
white = "#FFFFFF"

