[mgr]

prepend_keymap = [

# ─── Root ───────────────────────────────────────
	{ on = [ "g", "e" ],                run = "cd /etc/",                                   desc = "Go to /etc" },
	{ on = [ "g", "h" ],                run = "cd ~",                                       desc = "Go to home" },
	{ on = [ "g", "u" ],                run = "cd /usr/",                                   desc = "Go to /usr" },
	{ on = [ "g", "l" ],                run = "cd /usr/local",                              desc = "Go to /usr/local" },
	{ on = [ "g", "b" ],                run = "cd /usr/local/bin",                          desc = "Go to /usr/local/bin" },

# ─── Documents ─────────────────────────────────
	{ on = [ "g", "d", "." ],           run = "cd ~/Documents",                             desc = "Go to Documents" },
	{ on = [ "g", "d", "a", "c" ],      run = "cd ~/Documents/Academics/",                  desc = "Go to Academics" },
	{ on = [ "g", "d", "a", "d" ],      run = "cd ~/Documents/Admin/",                      desc = "Go to Admin" },
	{ on = [ "g", "d", "c" ],           run = "cd ~/Documents/config/",                     desc = "Go to config" },
	{ on = [ "g", "d", "f" ],           run = "cd ~/Documents/Finance/",                    desc = "Go to Finance" },
	{ on = [ "g", "d", "k" ],           run = "cd ~/Documents/Kingdom/",                    desc = "Go to Kingdom" },
	{ on = [ "g", "d", "m" ],           run = "cd ~/Documents/mac-brain/",                  desc = "Go to mac-brain" },
	{ on = [ "g", "d", "r" ],           run = "cd ~/Documents/Resources/",                  desc = "Go to Resources" },
	{ on = [ "g", "d", "z" ],           run = "cd ~/Documents/Zotero/",                     desc = "Go to Zotero" },

# ─── ML ────────────────────────────────────────
	{ on = [ "g", "m", "." ],           run = "cd ~/Documents/ML/",                         desc = "Go to ML" },
	{ on = [ "g", "m", "c" ],           run = "cd ~/Documents/ML/Courses/",                 desc = "Go to ML/Courses" },
	{ on = [ "g", "m", "p" ],           run = "cd ~/Documents/ML/Portfolio/",               desc = "Go to ML/Portfolio" },
	{ on = [ "g", "m", "j" ],           run = "cd ~/Documents/ML/Projects/",                desc = "Go to ML/Projects" },
	{ on = [ "g", "m", "r" ],           run = "cd ~/Documents/ML/Resources/",               desc = "Go to ML/Resources" },
	{ on = [ "g", "m", "s" ],           run = "cd ~/Documents/ML/Sandbox/",                 desc = "Go to ML/Sandbox" },
	{ on = [ "g", "m", "t" ],           run = "cd ~/Documents/ML/Tutorials/",               desc = "Go to ML/Tutorials" },
	{ on = [ "g", "m", "w" ],           run = "cd ~/Documents/ML/Website/marcocamilo.com",  desc = "Go to ML Website" },

# ─── Profession ────────────────────────────────
	{ on = [ "g", "d", "p", "." ],      run = "cd ~/Documents/Profession/",                 desc = "Go to Profession" },
	{ on = [ "g", "d", "p", "w" ],      run = "cd ~/Documents/Profession/Work/",            desc = "Go to Profession/Work" },
	{ on = [ "g", "d", "p", "f" ],      run = "cd ~/Documents/Profession/Profile/",         desc = "Go to Profession/Profile" },
	{ on = [ "g", "d", "p", "p" ],      run = "cd ~/Documents/Profession/Portfolio/",       desc = "Go to Profession/Portfolio" },
	{ on = [ "g", "d", "p", "r" ],      run = "cd ~/Documents/Profession/Resources/",       desc = "Go to Profession/Resources" },

# ─── Config ────────────────────────────────────
	{ on = [ "g", "c", "." ],           run = "cd ~/config/",                               desc = "Go to dotfiles" },
	{ on = [ "g", "c", "a" ],           run = "cd ~/config/alacritty/.config/alacritty/",   desc = "Go to alacritty config" },
	{ on = [ "g", "c", "d", "s" ],      run = "cd ~/config/dunst/.config/dunst/",           desc = "Go to dunst config" },
	{ on = [ "g", "c", "d", "w", "l" ], run = "cd ~/config/dwl/.config/dwl/",               desc = "Go to dwl config" },
	{ on = [ "g", "c", "d", "w", "m" ], run = "cd ~/config/dwm/.config/suckless/dwm/",      desc = "Go to dwm config" },
	{ on = [ "g", "c", "e" ],           run = "cd ~/config/espanso/.config/espanso/",       desc = "Go to espanso config" },
	{ on = [ "g", "c", "f", "f" ],      run = "cd ~/config/fastfetch/.config/fastfetch/",   desc = "Go to fastfetch config" },
	{ on = [ "g", "c", "f", "z" ],      run = "cd ~/config/fzf/.config/fzf/",               desc = "Go to fzf config" },
	{ on = [ "g", "c", "l", "z" ],      run = "cd ~/config/lazygit/.config/lazygit/",       desc = "Go to lazygit config" },
	{ on = [ "g", "c", "l", "f" ],      run = "cd ~/config/lf/.config/lf/",                 desc = "Go to lf config" },
	{ on = [ "g", "c", "l", "s", "p" ], run = "cd ~/config/lsd/.config/lsd/",               desc = "Go to lsd config" },
	{ on = [ "g", "c", "n" ],           run = "cd ~/config/nvim/.config/nvim/",             desc = "Go to nvim config" },
	{ on = [ "g", "c", "p", "l", "y" ], run = "cd ~/config/polybar/.config/polybar/",       desc = "Go to polybar config" },
	{ on = [ "g", "c", "s", "c" ],      run = "cd ~/config/scripts/.scripts/",              desc = "Go to scripts" },
	{ on = [ "g", "c", "s", "t" ],      run = "cd ~/config/starship/.config/starship/",     desc = "Go to starship config" },
	{ on = [ "g", "c", "t" ],           run = "cd ~/config/tmux/.config/tmux/",             desc = "Go to tmux config" },
	{ on = [ "g", "c", "x" ],           run = "cd ~/config/x/",                             desc = "Go to X config" },
	{ on = [ "g", "c", "y" ],           run = "cd ~/config/yazi/.config/yazi/",             desc = "Go to yazi config" },
	{ on = [ "g", "c", "z" ],           run = "cd ~/config/zsh/.config/zsh/",               desc = "Go to zsh config" }

]
